server:
  port: 9300
#  ssl:    
#    enabled: true
#    key-alias: zmgateway
#    key-store-password: 820401
#    key-store: classpath:zmgatewaykeystore.p12
#    key-store-type: PKCS12

spring:
  application:
    name: gateway
  cloud:
    consul:
      #host: 192.168.6.103  #dev
      host: 127.0.0.1        
      port: 8500
      discovery:
        registerHealthCheck: false
        scheme: https
        healthCheckInterval: 15s
        instanceId: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        preferIpAddress: true
        #ipAddress: ${spring.cloud.client.ip-address}
        port: ${server.port}
    gateway:
      #httpclient:        
        #ssl:          
          #handshake-timeout-millis: 10000
          #close-notify-flush-timeout-millis: 3000
          #close-notify-read-timeout-millis: 0
      locator:
        enable: true
      filter:
        remove-non-proxy-headers:
          headers:
          - dummy
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#          - Path=/user/**
#          filters:
#          - StripPrefix=1
  zipkin:
    enable: true
    baseUrl: http://127.0.0.1:9001
  sleuth:
    sampler:
      percentage: 1        
#actuator
management:
  endpoint:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  security:
    enabled: false